### ISSUE TITLE
Doesn't include 6to5 polyfill?

### ISSUE THREAD

**Issue by dmaj7no5th** [6to5/6to5-jest#5]
Attempting to use the stock example here, but the tests are throwing an error when running into `Object.assign` in my script.

`TypeError: Object function Object() { [native code] } has no method 'assign'`

Is there an obvious config I'm missing to include the 6to5 polyfill that shims those methods?

**Comment by sebmck** [comment]
@dmaj7no5th `Object.assign` was removed from internal use by all transformers/helpers in 2.7.3. You'll have to include the polyfill manually at the top of your main file. Only reason I can't include the polyfill is because in `jest`, and please correct me if I'm wrong as I'm more than happy to fix/improve it, but `scriptPreprocessor`s don't have access to the actual test execution context which means that we can't execute any code in it. Again, I'm not sure where I got this from but I'm happy to be proven wrong.

**Comment by dmaj7no5th** [comment]
Hmm..  well putting it on the main file wouldn't work since jest is testing each module in isolation. Looks like adding a shim to the test file manages to work so long as you tell jest not to mock it beforehand:

```
jest.dontMock('es6-shim');
import 'es6-shim';

describe('module tests', function () {
    it('should should test something', function () {
        import something from '../some-file.js';
        // test code...
    });
});
```

Oh well, not a terribly big deal. Just have to remember to add that to all my test files as I go.

**Comment by sebmck** [comment]
@dmaj7no5th Yeah, I partially remembered that Jest sandboxed every test file. Sorry there aren't any other options. I'll close this for now as it's *basically* been resolved. Thanks!
